<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.jdbc.object.StoredProcedureTests" tests="18" skipped="0" failures="0" errors="0" timestamp="2016-11-10T07:40:43" hostname="XB-20161010YVDY" time="0.039">
  <properties/>
  <testcase name="testStoredProcedureSkippingResultsProcessing" classname="org.springframework.jdbc.object.StoredProcedureTests" time="0.002"/>
  <testcase name="testMissingParameter" classname="org.springframework.jdbc.object.StoredProcedureTests" time="0.001"/>
  <testcase name="testStoredProcedureWithUndeclaredResults" classname="org.springframework.jdbc.object.StoredProcedureTests" time="0.001"/>
  <testcase name="testNumericWithScale" classname="org.springframework.jdbc.object.StoredProcedureTests" time="0.003"/>
  <testcase name="testAddInvoices" classname="org.springframework.jdbc.object.StoredProcedureTests" time="0.001"/>
  <testcase name="testStoredProcedureSkippingUndeclaredResults" classname="org.springframework.jdbc.object.StoredProcedureTests" time="0.001"/>
  <testcase name="testNoSuchStoredProcedure" classname="org.springframework.jdbc.object.StoredProcedureTests" time="0.007"/>
  <testcase name="testStoredProcedureWithResultSet" classname="org.springframework.jdbc.object.StoredProcedureTests" time="0.002"/>
  <testcase name="testParameterMapper" classname="org.springframework.jdbc.object.StoredProcedureTests" time="0.004"/>
  <testcase name="testSqlTypeValue" classname="org.springframework.jdbc.object.StoredProcedureTests" time="0.003"/>
  <testcase name="testStoredProcedureConfiguredViaJdbcTemplateWithCustomExceptionTranslator" classname="org.springframework.jdbc.object.StoredProcedureTests" time="0.001"/>
  <testcase name="testStoredProcedureWithResultSetMapped" classname="org.springframework.jdbc.object.StoredProcedureTests" time="0.002"/>
  <testcase name="testUnnamedParameter" classname="org.springframework.jdbc.object.StoredProcedureTests" time="0.001"/>
  <testcase name="testAddInvoicesWithinTransaction" classname="org.springframework.jdbc.object.StoredProcedureTests" time="0.001"/>
  <testcase name="testAddInvoicesUsingObjectArray" classname="org.springframework.jdbc.object.StoredProcedureTests" time="0.002"/>
  <testcase name="testNullArg" classname="org.springframework.jdbc.object.StoredProcedureTests" time="0.001"/>
  <testcase name="testStoredProcedureConfiguredViaJdbcTemplate" classname="org.springframework.jdbc.object.StoredProcedureTests" time="0.001"/>
  <testcase name="testStoredProcedureExceptionTranslator" classname="org.springframework.jdbc.object.StoredProcedureTests" time="0.003"/>
  <system-out><![CDATA[15:40:43.118 [Test worker] WARN  org.springframework.jdbc.support.SQLErrorCodesFactory - Error while extracting database product name - falling back to empty error codes
org.springframework.jdbc.support.MetaDataAccessException: DatabaseMetaData returned by Connection [Mock for Connection, hashCode: 1608929223] was null
	at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:287) ~[main/:?]
	at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:319) ~[main/:?]
	at org.springframework.jdbc.support.SQLErrorCodesFactory.getErrorCodes(SQLErrorCodesFactory.java:214) [main/:?]
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.setDataSource(SQLErrorCodeSQLExceptionTranslator.java:134) [main/:?]
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.<init>(SQLErrorCodeSQLExceptionTranslator.java:97) [main/:?]
	at org.springframework.jdbc.support.JdbcAccessor.getExceptionTranslator(JdbcAccessor.java:99) [main/:?]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:1099) [main/:?]
	at org.springframework.jdbc.core.JdbcTemplate.call(JdbcTemplate.java:1135) [main/:?]
	at org.springframework.jdbc.object.StoredProcedure.execute(StoredProcedure.java:142) [main/:?]
	at org.springframework.jdbc.object.StoredProcedureTests$NoSuchStoredProcedure.execute(StoredProcedureTests.java:527) [test/:?]
	at org.springframework.jdbc.object.StoredProcedureTests.testNoSuchStoredProcedure(StoredProcedureTests.java:100) [test/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.12.jar:4.12]
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239) [junit-4.12.jar:4.12]
	at org.junit.rules.RunRules.evaluate(RunRules.java:20) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114) [gradle-testing-jvm-3.1.jar:3.1]
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57) [gradle-testing-jvm-3.1.jar:3.1]
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66) [gradle-testing-jvm-3.1.jar:3.1]
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51) [gradle-testing-base-3.1.jar:3.1]
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35) [gradle-messaging-3.1.jar:3.1]
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24) [gradle-messaging-3.1.jar:3.1]
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32) [gradle-messaging-3.1.jar:3.1]
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93) [gradle-messaging-3.1.jar:3.1]
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source) [?:?]
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109) [gradle-testing-base-3.1.jar:3.1]
	at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35) [gradle-messaging-3.1.jar:3.1]
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24) [gradle-messaging-3.1.jar:3.1]
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377) [gradle-messaging-3.1.jar:3.1]
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54) [gradle-base-services-3.1.jar:3.1]
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40) [gradle-base-services-3.1.jar:3.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
